name: Run Tests

on:
  workflow_call:
    inputs: {}

jobs:
  linux:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        go-version: [1.19.x]

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Set up Go modules cache
      uses: actions/cache@v3
      env:
        cache-name: cache-go-modules
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go${{ matrix.go-version }}-build-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go${{ matrix.go-version }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-go${{ matrix.go-version }}-build-
          ${{ runner.os }}-go${{ matrix.go-version }}-

    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # - name: golangci-lint
    #   uses: golangci/golangci-lint-action@v3
    #   with:
    #     args: --issues-exit-code=0

    - name: Run tests
      run: |
        make build
        make cover

    - name: Prepare release
      if: github.ref == 'refs/heads/main' && github.event.type != 'pull_request'
      uses: labd/changie-release-action@v0.1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        release-workflow: 'release.yaml'
